2024-09-22 21:56:56,109 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Lesson0\pythonProject2\tests_12_4.py", line 19, in test_run
    runner_ = HumanMoveTests.Runner(0)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\Lesson0\pythonProject2\HumanMoveTests.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-22 21:56:56,120 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Lesson0\pythonProject2\tests_12_4.py", line 9, in test_walk
    walker = HumanMoveTests.Runner('first', -5)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\Lesson0\pythonProject2\HumanMoveTests.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
